name: Keith
desc: a software engineer with a passion for Kubernetes, cloud technology, and developer tooling.
about:
  - 🌱 I'm working on improving my **Go and Neovim** skills
  - 💬 Ask me about **Kubernetes, Containers, or Linux**
langs:
  active:
    - href: https://aws.amazon.com
      name: amazonwebservices
      type: wordmark
    - href: https://azure.microsoft.com/en-in/
      name: azure
    - href: https://www.gnu.org/software/bash/
      name: bash
    - href: https://www.w3schools.com/css/
      name: css3
    - href: https://www.docker.com/
      name: docker
    - href: https://cloud.google.com
      name: googlecloud
    - href: https://git-scm.com/
      name: git
    - href: https://golang.org
      name: go
    - href: https://www.w3.org/html/
      name: html5
    - href: https://kubernetes.io
      name: kubernetes
    - href: https://www.linux.org/
      name: linux
  previous:
    - href: https://circleci.com
      name: circleci
      type: plain
    - href: https://www.w3schools.com/cpp/
      name: cplusplus
    - href: https://www.w3schools.com/cs/
      name: csharp
    - href: https://d3js.org/
      name: d3js
    - href: https://www.djangoproject.com/
      name: django
      type: plain
    - href: https://dotnet.microsoft.com/
      name: dot-net
    - href: https://firebase.google.com/
      name: firebase
    - href: https://flask.palletsprojects.com/
      name: flask
    - href: https://flutter.dev
      name: flutter
    - href: https://grafana.com
      name: grafana
    - href: https://heroku.com
      name: heroku
    - href: https://www.java.com
      name: java
    - href: https://developer.mozilla.org/en-US/docs/Web/JavaScript
      name: javascript
    - href: https://www.jenkins.io
      name: jenkins
    - href: https://laravel.com/
      name: laravel
    - href: https://mariadb.org/
      name: mariadb
    - href: https://www.mysql.com/
      name: mysql
    - href: https://www.nginx.com
      name: nginx
    - href: https://nodejs.org
      name: nodejs
    - href: https://www.oracle.com/
      name: oracle
    - href: https://www.php.net
      name: php
    - href: https://www.postgresql.org
      name: postgresql
    - href: https://postman.com
      name: postman
    - href: https://www.python.org
      name: python
    - href: https://rubyonrails.org
      name: rails
      type: wordmark
    - href: https://reactjs.org/
      name: react
    - href: https://redis.io
      name: redis
    - href: https://www.ruby-lang.org/en/
      name: ruby
    - href: https://www.selenium.dev
      name: selenium
    - href: https://www.sqlite.org/
      name: sqlite
    - href: https://www.typescriptlang.org/
      name: typescript
    - href: https://vuejs.org/
      name: vuejs
