name: Keith
desc: a software engineer with a passion for Kubernetes, cloud technology, and developer tooling.
about:
  - 🌱 I'm working on improving my **Go and Neovim** skills
  - 💬 Ask me about **Kubernetes, Containers, or Linux**
langs:
  active:
    - href: https://aws.amazon.com
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg
      name: aws
    - href: https://azure.microsoft.com/en-in/
      img: https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg
      name: azure
    - href: https://www.gnu.org/software/bash/
      img: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bash/bash-original.svg
      name: bash
    - href: https://www.w3schools.com/css/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg
      name: css3
    - href: https://www.docker.com/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg
      name: docker
    - href: https://cloud.google.com
      img: https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg
      name: gcp
    - href: https://git-scm.com/
      img: https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg
      name: git
    - href: https://golang.org
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/go/go-original.svg
      name: go
    - href: https://www.w3.org/html/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg
      name: html5
    - href: https://kubernetes.io
      img: https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg
      name: kubernetes
    - href: https://www.linux.org/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg
      name: linux
  previous:
    - href: https://circleci.com
      img: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/circleci/circleci-plain.svg
      name: circleci
    - href: https://www.w3schools.com/cpp/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg
      name: cplusplus
    - href: https://www.w3schools.com/cs/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original.svg
      name: csharp
    - href: https://d3js.org/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/d3js/d3js-original.svg
      name: d3js
    - href: https://www.djangoproject.com/
      img: https://cdn.worldvectorlogo.com/logos/django.svg
      name: django
    - href: https://dotnet.microsoft.com/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/dot-net/dot-net-original-wordmark.svg
      name: dotnet
    - href: https://firebase.google.com/
      img: https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg
      name: firebase
    - href: https://flask.palletsprojects.com/
      img: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flask/flask-original.svg
      name: flask
    - href: https://flutter.dev
      img: https://www.vectorlogo.zone/logos/flutterio/flutterio-icon.svg
      name: flutter
    - href: https://grafana.com
      img: https://www.vectorlogo.zone/logos/grafana/grafana-icon.svg
      name: grafana
    - href: https://heroku.com
      img: https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg
      name: heroku
    - href: https://www.java.com
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg
      name: java
    - href: https://developer.mozilla.org/en-US/docs/Web/JavaScript
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg
      name: javascript
    - href: https://www.jenkins.io
      img: https://www.vectorlogo.zone/logos/jenkins/jenkins-icon.svg
      name: jenkins
    - href: https://laravel.com/
      img: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-original.svg
      name: laravel
    - href: https://mariadb.org/
      img: https://www.vectorlogo.zone/logos/mariadb/mariadb-icon.svg
      name: mariadb
    - href: https://www.mysql.com/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg
      name: mysql
    - href: https://www.nginx.com
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg
      name: nginx
    - href: https://nodejs.org
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg
      name: nodejs
    - href: https://www.oracle.com/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/oracle/oracle-original.svg
      name: oracle
    - href: https://www.php.net
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg
      name: php
    - href: https://www.postgresql.org
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg
      name: postgresql
    - href: https://postman.com
      img: https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg
      name: postman
    - href: https://www.python.org
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg
      name: python
    - href: https://rubyonrails.org
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/rails/rails-original-wordmark.svg
      name: rails
    - href: https://reactjs.org/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg
      name: react
    - href: https://redis.io
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/redis/redis-original-wordmark.svg
      name: redis
    - href: https://www.ruby-lang.org/en/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/ruby/ruby-original.svg
      name: ruby
    - href: https://www.selenium.dev
      img: https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/selenium-logo.svg
      name: selenium
    - href: https://www.sqlite.org/
      img: https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg
      name: sqlite
    - href: https://www.typescriptlang.org/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg
      name: typescript
    - href: https://vuejs.org/
      img: https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original-wordmark.svg
      name: vuejs
